name: rune
version: 0.1.0.0
github: "shmul95/glados"
license: BSD-3-Clause
author: "Samuel"
maintainer: "samuel.gross@epitech.eu"
copyright: "2025 Samuel"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/shmul95/glados#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec

ghc-options:
  - -Wall
  - -Wextra
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  rune-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rune

tests:
  rune-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rune
      - tasty
      - tasty-hunit
      - directory
